apiVersion: ogvalt.dev/v1alpha1
kind: ModelDeployment
metadata:
  name: modeldeployment-dev
  namespace: triton
  annotations:
    modelOrigin: custom
spec:
  jobSpec:
    backoffLimit: 0
    ttlSecondsAfterFinished: 60
    template:
      spec:
        restartPolicy: Never
        containers:
         - name: model-deployment
           image: busybox:latest
           args:
            - /bin/sh
            - -c
            - |
              custom_model_deployment_executable --src=/src --dest=?
              # TODO: figure out how to pass tritonserver pod url to the executable
           
