apiVersion: ogvalt.dev/v1alpha1
kind: ModelDeployment
metadata:
  name: modeldeployment-s3-dev
  namespace: triton
spec:
  model:
    config:
      name: simple
      platform: tensorflow_graphdef
      max_batch_size: 8
      input:
        - name: INPUT0
          data_type: TYPE_INT32
          dims:
            - '16'
        - name: INPUT1
          data_type: TYPE_INT32
          dims:
            - '16'
      output:
        - name: OUTPUT0
          data_type: TYPE_INT32
          dims:
            - '16'
        - name: OUTPUT1
          data_type: TYPE_INT32
          dims:
            - '16'
    labels:
      - class_0
      - class_1
    versions:
      - version: 1
        files:
          - name: model.graphdef
            source: s3://bucket/model_repository/model.graphdef

  jobTemplate:
    provider: operator
    spec:
      source: s3
      auth:
        type: configMap
        name: operator-config
