apiVersion: ogvalt.dev/v1alpha1
kind: ModelDeployment
metadata:
  name: modeldeployment-s3-dev
  namespace: triton
  annotations:
    modelOrigin: s3
spec:
  model:
    modelConfig: 
      name: Model
      max_batch_size: 2
      input:
      - name: one
        data_type: TYPE_INT32
        dims:
        - '1'
      - name: two
        data_type: TYPE_FP32
        dims:
        - '1'
      output:
      - name: one
        data_type: TYPE_INT32
        dims:
        - '1'
      - name: two
        data_type: TYPE_FP32
        dims:
        - '1'
      instance_group:
      - count: 1
        kind: KIND_CPU
      sequence_batching:
        max_sequence_idle_microseconds: '300000000000'
        control_input:
        - name: START
          control:
          - fp32_false_true:
            - 0.0
            - 1.0
        - name: END
          control:
          - kind: CONTROL_SEQUENCE_END
            fp32_false_true:
            - 0.0
            - 1.0
        oldest: {}
      parameters:
        two:
          string_value: '0.1'
        one:
          string_value: '0.5'
      backend: python
    labels: ...  # output-labels-file
    versions:
      - version: 1
        files:
        - name: model.plan  #  triton specific name
          source: s3://bucket/model_repository/checkpoint.plan

      - version: 2
        files:
        - name: model.onnx  #  triton specific name
          source: s3://bucket/model_repository/checkpoint.onnx

      - version: 3
        files:
        - name: model.onnx/model.onnx
          source: s3://bucket/model_repository/model/checkpoint.onnx
        - name: model.onnx/other_onnx_file.onnx  
          source: s3://bucket/model_repository/model/other_onnx_file.onnx

      - version: 4
        files:
        - name: model.savedmodel/saved_model.pb
          source: s3://bucket/model_repository/model.savemodel/saved_model.pb
        - name: model.savedmodel/variables/variables.data-00000-of-00001
          source: s3://bucket/model_repository/model.savemodel/variables/variables.data-00000-of-00001
        - name: model.savedmodel/variables/variables.index
          source: s3://bucket/model_repository/model.savemodel/variables/variables.index

  jobTemplate:
    type: operator | user-prodived # default operator
    image: popovych-labs/model-deployment-job-s3:latest
    configMap: aws-config
    
