apiVersion: ogvalt.dev/v1alpha1
kind: ModelDeployment
metadata:
  name: modeldeployment-s3-dev
  namespace: triton
spec:
  model:
    config:
      name: simple
      platform: tensorflow_graphdef
      max_batch_size: 8
      input:
        - name: INPUT0
          data_type: TYPE_INT32
          dims:
            - '16'
        - name: INPUT1
          data_type: TYPE_INT32
          dims:
            - '16'
      output:
        - name: OUTPUT0
          data_type: TYPE_INT32
          dims:
            - '16'
        - name: OUTPUT1
          data_type: TYPE_INT32
          dims:
            - '16'
    labels: ... # output-labels-file
    versions:
      - version: 1
        files:
          - name: model.plan #  triton specific name
            source: s3://bucket/model_repository/model.graphdef

  jobTemplate:
    provider: operator | user
    spec:
      source: s3
      auth:
        type: configMap
        name: aws-creds

      image: popovych-labs/model-deployment-job-s3:latest
      configMap: aws-config