apiVersion: ogvalt.dev/v1alpha1
kind: ModelDeployment
metadata:
  name: modeldeployment-dev
  namespace: triton
  annotations:
    modelOrigin: s3
spec:
  modelSource: s3://bucket/model_repository/model.plan
  jobTemplate:
    backoffLimit: 0
    ttlSecondsAfterFinished: 60
    template:
      spec:
        restartPolicy: Never
        containers:
         - name: model-deployment
           image: busybox:latest
           envFrom:
           - configMapRef:
              name: aws-config
