apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modeldeployments.{{ .Values.crd.group }}
spec:
  group: '{{ .Values.crd.group }}'
  names:
    kind: ModelDeployment
    plural: modeldeployments
    shortNames:
    - modeldepls
    - modeldepl
    - mds
    - md
    singular: modeldeployment
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The children pods created.
      jsonPath: .status.create_fn.children
      name: Children
      priority: 0
      type: string
    - description: Model status.
      jsonPath: .status.model_status
      name: Status
      priority: 0
      type: string
    - description: Model source.
      jsonPath: .spec.modelSource
      name: Model Source
      priority: 0
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              jobTemplate:
                default: {}
                title: Jobtemplate
                type: object
                x-kubernetes-preserve-unknown-fields: 'true'
              model:
                properties:
                  labels:
                    default: []
                    items:
                      type: string
                    title: Labels
                    type: array
                  modelConfig:
                    allOf:
                    - properties:
                        input:
                          items: {}
                          title: Input
                          type: array
                        max_batch_size:
                          title: Max Batch Size
                          type: integer
                        output:
                          items: {}
                          title: Output
                          type: array
                        platform:
                          title: Platform
                          type: string
                      required:
                      - max_batch_size
                      - input
                      - output
                      - platform
                      title: ModelConfigSpec
                      type: object
                    x-kubernetes-preserve-unknown-fields: 'true'
                  versions:
                    items:
                      properties:
                        files:
                          items:
                            properties:
                              name:
                                title: Name
                                type: string
                              source:
                                title: Source
                                type: string
                            required:
                            - name
                            - source
                            title: FileSpec
                            type: object
                          title: Files
                          type: array
                        version:
                          title: Version
                          type: integer
                      required:
                      - version
                      - files
                      title: VersionSpec
                      type: object
                    title: Versions
                    type: array
                required:
                - modelConfig
                - versions
                title: ModelSpec
                type: object
            required:
            - model
            title: ModelDeploymentSpec
            type: object
        type: object
    served: true
    storage: true

