apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modeldeployments.{{ .Values.crd.group }}
spec:
  group: '{{ .Values.crd.group }}'
  names:
    kind: ModelDeployment
    plural: modeldeployments
    shortNames:
    - modeldepls
    - modeldepl
    - mds
    - md
    singular: modeldeployment
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The children pods created.
      jsonPath: .status.create_fn.children
      name: Children
      priority: 0
      type: string
    - description: Model status.
      jsonPath: .status.model_status
      name: Status
      priority: 0
      type: string
    - description: Model source.
      jsonPath: .spec.modelSource
      name: Model Source
      priority: 0
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              jobTemplate:
                properties:
                  backoffLimit:
                    title: Backofflimit
                    type: integer
                  template:
                    properties:
                      spec:
                        properties:
                          containers:
                            default: []
                            items:
                              properties:
                                env:
                                  default: []
                                  items:
                                    properties:
                                      name:
                                        title: Name
                                        type: string
                                      value:
                                        title: Value
                                        type: string
                                    required:
                                    - name
                                    - value
                                    title: EnvironmentVariable
                                    type: object
                                  title: Env
                                  type: array
                                envFrom:
                                  default: []
                                  items:
                                    properties:
                                      configMapRef:
                                        properties:
                                          name:
                                            title: Name
                                            type: string
                                        required:
                                        - name
                                        title: configMapRefElement
                                        type: object
                                    required:
                                    - configMapRef
                                    title: configMapRefObj
                                    type: object
                                  title: Envfrom
                                  type: array
                                image:
                                  title: Image
                                  type: string
                                name:
                                  title: Name
                                  type: string
                                volumeMounts:
                                  default: []
                                  items:
                                    properties:
                                      mountPath:
                                        title: Mountpath
                                        type: string
                                      name:
                                        title: Name
                                        type: string
                                    required:
                                    - name
                                    - mountPath
                                    title: VolumeMount
                                    type: object
                                  title: Volumemounts
                                  type: array
                              required:
                              - name
                              - image
                              title: Container
                              type: object
                            title: Containers
                            type: array
                          restartPolicy:
                            default: Never
                            title: Restartpolicy
                            type: string
                          volumes:
                            default: []
                            items:
                              properties:
                                configMap:
                                  properties:
                                    configMapRef:
                                      properties:
                                        name:
                                          title: Name
                                          type: string
                                      required:
                                      - name
                                      title: configMapRefElement
                                      type: object
                                  required:
                                  - configMapRef
                                  title: configMapRefObj
                                  type: object
                                name:
                                  title: Name
                                  type: string
                              required:
                              - name
                              - configMap
                              title: Volumes
                              type: object
                            title: Volumes
                            type: array
                        title: Spec
                        type: object
                    required:
                    - spec
                    title: PodTemplate
                    type: object
                  ttlSecondsAfterFinished:
                    title: Ttlsecondsafterfinished
                    type: integer
                required:
                - backoffLimit
                - ttlSecondsAfterFinished
                - template
                title: JobTemplate
                type: object
              modelSource:
                title: Modelsource
                type: string
            required:
            - modelSource
            - jobTemplate
            title: ModelDeploymentSpec
            type: object
        type: object
    served: true
    storage: true

