version: '3'

vars:
  DOCKER: docker
  VERSION: latest

tasks:
  docker-build-operator-dev:
    desc: Building docker image
    vars: 
      IMAGE_NAME: ${ORGANIZATION}/model-deployment-operator:{{.VERSION}}-dev
    cmds:
      - |
        {{.DOCKER}} build \
          --build-arg IMAGE_TAG=3.10 \
          --progress=plain \
          --target operator_image \
          --tag {{.IMAGE_NAME}} \
          --file ${PWD}/docker/operator/Dockerfile \
          ${PWD}

  docker-build-operator-prod:
    desc: Building docker image
    vars: 
      IMAGE_NAME: ${ORGANIZATION}/model-deployment-operator:{{.VERSION}}
    cmds:
      - |
        {{.DOCKER}} build \
          --build-arg IMAGE_TAG=3.10-alpine \
          --progress=plain \
          --target operator_image \
          --tag {{.IMAGE_NAME}} \
          --file ${PWD}/docker/operator/Dockerfile \
          ${PWD}

  docker-run-operator:
    desc: Building docker image
    vars: 
      IMAGE_NAME: ${ORGANIZATION}/model-deployment-operator:{{.VERSION}}
    cmds:
      - |
        {{.DOCKER}} run \
          --rm -it --network="host" \
          --name model_deployment_operator_instance \
          -p 8003:8003 \
          {{.IMAGE_NAME}}

  docker-build-jobs:
    desc: Building docker image
    vars: 
      IMAGE_NAME: ${ORGANIZATION}/model-deployment-operator/job/s3:{{.VERSION}}-dev
    cmds:
      - |
        {{.DOCKER}} build \
          --progress=plain \
          --target job_image \
          --tag {{.IMAGE_NAME}} \
          --file ${PWD}/docker/jobs/Dockerfile \
          ${PWD}

  docker-run-jobs:
    desc: Building docker image
    vars: 
      IMAGE_NAME: ${ORGANIZATION}/model-deployment-jobs:{{.VERSION}}
    cmds:
      - |
        {{.DOCKER}} run \
          --rm -it --network="host" \
          --name model_deployment_operator_instance \
          -p 8003:8003 \
          {{.IMAGE_NAME}}
  